"""initial schema

Revision ID: 2e63c85b8716
Revises: 
Create Date: 2026-04-07 07:40:06.901671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e63c85b8716'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('season', sa.String(), nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('home_goals', sa.Integer(), nullable=False),
    sa.Column('away_goals', sa.Integer(), nullable=False),
    sa.Column('home_xg', sa.Float(), nullable=False),
    sa.Column('away_xg', sa.Float(), nullable=False),
    sa.Column('home_shots', sa.Integer(), nullable=False),
    sa.Column('away_shots', sa.Integer(), nullable=False),
    sa.Column('home_shots_on_target', sa.Integer(), nullable=False),
    sa.Column('away_shots_on_target', sa.Integer(), nullable=False),
    sa.Column('home_deep', sa.Integer(), nullable=False),
    sa.Column('away_deep', sa.Integer(), nullable=False),
    sa.Column('home_ppda', sa.Float(), nullable=False),
    sa.Column('away_ppda', sa.Float(), nullable=False),
    sa.Column('home_win_prob', sa.Float(), nullable=False),
    sa.Column('draw_prob', sa.Float(), nullable=False),
    sa.Column('away_win_prob', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('actual_home_goals', sa.Integer(), nullable=True),
    sa.Column('actual_away_goals', sa.Integer(), nullable=True),
    sa.Column('actual_outcome', sa.String(), nullable=True),
    sa.Column('ml_home_win', sa.Float(), nullable=False),
    sa.Column('ml_draw', sa.Float(), nullable=False),
    sa.Column('ml_away_win', sa.Float(), nullable=False),
    sa.Column('ml_predicted_outcome', sa.String(), nullable=False),
    sa.Column('ml_correct', sa.Boolean(), nullable=True),
    sa.Column('ml_top_home_goals', sa.Integer(), nullable=False),
    sa.Column('ml_top_away_goals', sa.Integer(), nullable=False),
    sa.Column('ml_top_probability', sa.Float(), nullable=False),
    sa.Column('poisson_home_win', sa.Float(), nullable=False),
    sa.Column('poisson_draw', sa.Float(), nullable=False),
    sa.Column('poisson_away_win', sa.Float(), nullable=False),
    sa.Column('poisson_predicted_outcome', sa.String(), nullable=False),
    sa.Column('poisson_correct', sa.Boolean(), nullable=True),
    sa.Column('poisson_home_lambda', sa.Float(), nullable=False),
    sa.Column('poisson_away_lambda', sa.Float(), nullable=False),
    sa.Column('poisson_top_home_goals', sa.Integer(), nullable=False),
    sa.Column('poisson_top_away_goals', sa.Integer(), nullable=False),
    sa.Column('poisson_top_probability', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_features',
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('xg_for_avg', sa.Float(), nullable=False),
    sa.Column('xg_against_avg', sa.Float(), nullable=False),
    sa.Column('xg_overperformance', sa.Float(), nullable=False),
    sa.Column('shot_conversion', sa.Float(), nullable=False),
    sa.Column('sot_pct', sa.Float(), nullable=False),
    sa.Column('ppda', sa.Float(), nullable=False),
    sa.Column('deep_avg', sa.Float(), nullable=False),
    sa.Column('goals_for_avg', sa.Float(), nullable=False),
    sa.Column('goals_against_avg', sa.Float(), nullable=False),
    sa.Column('home_advantage', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('team_name')
    )
    op.create_table('teams',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('upcoming',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('home_team', sa.String(), nullable=False),
    sa.Column('away_team', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('ml_home_win', sa.Float(), nullable=False),
    sa.Column('ml_draw', sa.Float(), nullable=False),
    sa.Column('ml_away_win', sa.Float(), nullable=False),
    sa.Column('ml_predicted_outcome', sa.String(), nullable=False),
    sa.Column('ml_top_home_goals', sa.Integer(), nullable=False),
    sa.Column('ml_top_away_goals', sa.Integer(), nullable=False),
    sa.Column('ml_top_probability', sa.Float(), nullable=False),
    sa.Column('poisson_home_win', sa.Float(), nullable=False),
    sa.Column('poisson_draw', sa.Float(), nullable=False),
    sa.Column('poisson_away_win', sa.Float(), nullable=False),
    sa.Column('poisson_predicted_outcome', sa.String(), nullable=False),
    sa.Column('poisson_home_lambda', sa.Float(), nullable=False),
    sa.Column('poisson_away_lambda', sa.Float(), nullable=False),
    sa.Column('poisson_top_home_goals', sa.Integer(), nullable=False),
    sa.Column('poisson_top_away_goals', sa.Integer(), nullable=False),
    sa.Column('poisson_top_probability', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upcoming')
    op.drop_table('teams')
    op.drop_table('team_features')
    op.drop_table('predictions')
    op.drop_table('matches')
    # ### end Alembic commands ###
